version: '3.8'

services:
  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "8000:8000"
    volumes:
      - ./services/user-service:/app
    env_file:
      - .env

  recommendation-service:
    build: ./services/recommendation-service
    container_name: recommendation-service
    ports:
      - "8001:8001"
    volumes:
      - ./services/recommendation-service:/app
