version: '3.8'

services:
  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "8000:8000"
    volumes:
      - ./services/user-service:/app
    env_file:
      - .env

  fastapi-service:
    build: ./services/fastapi-service
    container_name: fastapi-service
    ports:
      - "8001:8000"
    volumes:
      - ./services/fastapi-service:/app
